describe("rewin", function()
  it("is requireable", function()
    require("rewin")
  end)

  it("handles false map triggers and empty options", function()
    local rewin = require("rewin")
    rewin.setup({})
    rewin.closeWin()
    -- rewin.makeWin("V", {})
    rewin.winSwitch({})
  end
  )

  it("Can set the specific 'R' mapping", function()
    local rewin = require("rewin")
    rewin.setup({})
    rewin.setBuf()
  end)

  it("Handles no marks being set", function()
    local rewin = require("rewin")
    rewin.setup({})
    vim.cmd('delmarks A-Z0-9')
    rewin.makeWin("V", {})
  end)

  it("combination of functions in unpredictable order", function()
    local rewin = require("rewin")
    rewin.setup({})
    local beforeNum = #vim.inspect(vim.api.nvim_list_wins())
    rewin.closeWin()
    rewin.winSwitch({})
    local afterNum = #vim.inspect(vim.api.nvim_list_wins())
    assert(beforeNum == afterNum, "the number of windows open is not consistent")

  end)

  it("Sets window as not focusable", function()
    local rewin =require("rewin")
    rewin.makeWin("R",{})
    vim.cmd('wincmd w')
  end)
end
)
